### ISSUE TITLE
Error during WalletKit initialization: TimeoutCancellationException: Timed out waiting for 10000 ms

### ISSUE THREAD

**Issue by ShengXiuyan** [reown-com/reown-kotlin#19]
I'm using the reown-kotlin library in my Android project with the following dependencies in my build.gradle:
```
implementation(platform("com.reown:android-bom:1.0.0"))
implementation("com.reown:android-core")
implementation("com.reown:walletkit")
```
Here is my code:
```
CoreClient.initialize(
    application = this,
    projectId = projectId,
    connectionType = ConnectionType.AUTOMATIC,
    metaData = getAppMetaData(),
    onError = { error ->
        // Error handling
    }
)
```

```
WalletKit.initialize(
    Wallet.Params.Init(core = CoreClient),
    onSuccess = {
        
    },
    onError = {
        //Error(throwable=kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 10000 ms)
    }
)
```

When trying to initialize WalletKit, I get the following error: 
`kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 10000 ms`

I followed the documentation here: https://docs.reown.com/walletkit/android/usage, but the error occurs every time I call WalletKit.initialize. Are there any known causes of this issue or potential solutions?

**Comment by jakubuid** [comment]
Thanks for providing more details, unfortunately, I cannot reproduce it. Could you check our Kotlin Sample Wallet as a reference integration? 
See: https://github.com/reown-com/reown-kotlin/blob/develop/sample/wallet/src/main/kotlin/com/reown/sample/wallet/WalletKitApplication.kt#L74

**Comment by jakubuid** [comment]
This issue is resolve in [this](https://github.com/reown-com/reown-kotlin/pull/22) PR
