### ISSUE TITLE
Android Wallet Connect Session Authenticate

### ISSUE THREAD

**Issue by antonis-bc** [reown-com/reown-kotlin#27]
**Describe the bug**
I have migrated from Wallet connect Kotlin V2 sdk to Reown-kotlin v1.0.2 . Everything seems to work for the Regular flow as it's described [here](https://docs.reown.com/walletkit/android/one-click-auth#introduction) but when i am trying to test the Authenticated sessions flow, i am getting the following error: 
`throwable=java.lang.Throwable: JsonRpcInteractor: Unknown request params` 
After scanning the Wallet connect QR and try pairing using:
 
```
val pairingParams = Wallet.Params.Pair(scannedWCPairingUrl)
WalletKit.pair(Wallet.Params.Pair(pairingUrl))
```

 I am using this `https://react-auth-dapp.vercel.app/` which use to work as expected with [WalletConnectKotlinV2](https://github.com/WalletConnect/WalletConnectKotlinV2)

**Comment by jakubuid** [comment]
Hey!
The Dapp that you provided is deprecated, please use this: https://appkit-lab.reown.com/ for the tests and check if you see any issues, thanks!

**Comment by jakubuid** [comment]
For 1-ClickAuth testing please use: https://appkit-lab.reown.com/library/ethers-siwe/

**Comment by antonis-bc** [comment]
its working thanks!

**Comment by shownstrong** [comment]
Is there anyway to integration Appkit with the agp version 7.3.0 and kotlin version 1.8.0 ?
Our Android project already use Walletkit and not change the agp version 7.3.0 and kotlin version 1.8.0.
Now I want to use web3modal sdk (now is appkit), what should I do If I don't want to change agp and kotlin version?
