### ISSUE TITLE
AuthRequest Missing on WalletKit.WalletDelegate 

### ISSUE THREAD

**Issue by ecoin-finance** [reown-com/reown-kotlin#34]
Missing parts  on WalletKit.WalletDelegate 

AuthRequest
![image](https://github.com/user-attachments/assets/5100ea2d-f53b-4266-99a6-bad9480d5292)

**Comment by jakubuid** [comment]
Hey! Auth SDK has been deprecated. Please use 1-CA instead: https://docs.reown.com/walletkit/android/one-click-auth#approving-authentication-requests
